sudo: false
dist: trusty
language: python
cache: pip

services:
  - docker

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install --upgrade -r requirements-test.txt
  - pip install .

after_success: bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: "Test"
      python: '3.6'
      script: 
       - flake8 pathman/
       - mypy pathman/
       - pytest --integration

    - stage: release
      if: tag IS present
      python: '3.6'
      install: skip
      script: skip
      deploy:
        - provider: pypi
          on:
            all_branches: true
          user: blackfynn
          password: "$PYPI_PASSWORD"
          #server: https://test.pypi.org/legacy/ # uncomment to use test pypi
          distributions: sdist bdist_wheel
        - provider: script
          on:
            all_branches: true
